services:
  process1:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process1  
  process2: 
    build: ./
    ports:
      - 5001:5000
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process2
  process3: 
    build: ./
    ports:
      - 5002:5000
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process3