services:
  process1:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process1
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  process2:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process2
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  process3:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process3
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:stable-alpine3.21
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro 
    depends_on:
      process1:
        condition: service_healthy
      process2:
        condition: service_healthy
      process3:
        condition: service_healthy

  db:
    image: postgres:15.14
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: task-manager-db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  seeder:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    command: npm run seed

volumes:
  postgres_data: