auth_enabled: false # No passwords for internal Docker communication
server:
  http_listen_port: 3100 # receive logs

common:
  path_prefix: /loki
  storage:
    filesystem: # Save logs as files on the disk"
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb # A modern, fast storage format
      object_store: filesystem
      schema: v13
      index: { prefix: index_, period: 24h }
