services:
  process1:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process1
    restart: on-failure
    user: root
    entrypoint: ["sh", "-c", "chown -R app:app /app/logs && gosu app npx prisma generate && exec gosu app npm start"]
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      seeder:
        condition: service_completed_successfully
      
    volumes:
      - logs_data:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  process2:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      CONTAINER_NAME: process2
    restart: on-failure
    user: root
    entrypoint: ["sh", "-c", "chown -R app:app /app/logs && gosu app npx prisma generate && exec gosu app npm start"]
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      seeder:
        condition: service_completed_successfully
    volumes:
      - logs_data:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:stable-alpine3.21
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/deployment/task-flow/client:/var/www/task-flow-client:ro
      - /home/deployment/task-flow/admin:/var/www/task-flow-admin:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.desonames.xyz/fullchain.pem:/etc/nginx/certs/api.desonames.xyz/fullchain.pem:ro
      - /etc/letsencrypt/live/api.desonames.xyz/privkey.pem:/etc/nginx/certs/api.desonames.xyz/privkey.pem:ro
      - /etc/letsencrypt/live/task-flows.tech/fullchain.pem:/etc/nginx/certs/task-flows.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/task-flows.tech/privkey.pem:/etc/nginx/certs/task-flows.tech/privkey.pem:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      process1:
        condition: service_healthy
      process2:
        condition: service_healthy
      grafana:
        condition: service_started

  db:
    image: postgres:15.14
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: task-manager-db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task-manager-db -d tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrator:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    command: npx prisma migrate deploy
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma:ro
  
  seeder:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    command: npm run seed
    depends_on:
      migrator:
        condition: service_completed_successfully
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    # We don't usually need to expose 3100 to the world, 
    # but it's okay for testing.
    volumes:
      - ./infra/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - process1
      - process2

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./infra/promtail-config.yaml:/etc/promtail/config.yml
      # THESE TWO LINES ARE THE FIX:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this later!
    depends_on:
      - loki
      
volumes:
  postgres_data:
  logs_data: